/*
 < payload  < current int being written  < current bit getting written  < next int to be read  < next bit to be read  < precalculated values to efficiently mask reads  < precalculated values maximum possible value given bit length  */
var Communicator;
(function(e){(function(e){(function(c){var e=function(){function a(){this.data=[];this.rbit=this.rused=this.bit=this.used=0;this.mask=[];this.range=[]}a.prototype.Reset=function(){this.data=[];this.rbit=this.rused=this.bit=this.used=0;this.mask[0]=0;this.range[0]=0;var b;for(b=1;32>=b;b++)this.mask[b]=4294967295>>>32-b,this.range[b]=(1<<b-1>>>0)-1};a.prototype.InitRead=function(b){this.Reset();this.data=b};a.prototype.Get=function(b){if(32>=this.rbit+b){var d=this.data[this.rused]>>>0;var f=d>>>32-
this.rbit-b&this.mask[b];this.rbit+=b}else{var a=b+this.rbit-32;d=this.data[this.rused++]>>>0;f=d<<a>>>0&this.mask[b];d=this.data[this.rused]>>>0;f|=d>>>32-a;this.rbit+=b-32}return f};a.prototype.NumBytes=function(){return 4*(this.used+(this.bit?1:0))};return a}();c.BPack=e})(e.Internal||(e.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
(function(e){(function(v){(function(c){var p=function(){function a(b,d){this._captureNames=[];this._toCaptureTag={};this._toCamera={};this._toCuttingPlane={};this._toStyleTags={};this._toStyleMatrix={};this._toStyleVis={};this._principleStyleSegs={};this._principleNonStyleSegs={};this._toFrameMeshInstanceData={};this._viewer=b;this._hwfParser=d}a.prototype.checkParseCapture=function(b,d){var f=c.Util.extractUserOpt(b,"cad_cap_defns");f&&this.parseCaptureDefinitions(f);(f=c.Util.extractUserOpt(b,"cad_cap_style_defns"))&&
this.parseCaptureStyleDefinitions(f);(f=c.Util.extractUserOpt(b,"cad_default_capture"))&&this.parseDefaultCapture(f);null!==d&&((f=c.Util.extractUserOpt(b,"cm"))&&this.parseCaptureMarkup(f,d),(f=c.Util.extractUserOpt(b,"cn"))&&this.parseCaptureNonStyles(f,d),(f=c.Util.extractUserOpt(b,"cs"))&&this.parseCaptureStyles(f,d))};a.prototype.exportToModelStructure=function(){for(var b=!1,d=this._hwfParser.getHwfRootNode(),f=0;f<this._captureNames.length;f++){var a=this._toCaptureTag[this._captureNames[f]];
if(void 0!==a){var c=this._toCamera[a];if(void 0!==c){var k=void 0,g=this._toCuttingPlane[a];void 0!==g&&4===g.length&&(k=new e.Plane,k.normal.x=g[0],k.normal.y=g[1],k.normal.z=g[2],k.d=g[3]);g=this._toFrameMeshInstanceData[a];var n=[],m=this._principleNonStyleSegs[a];if(void 0!==m)for(var w=0;w<m.length;w++){var q=m[w];q=this._hwfParser.getSegmentPropertyManager().getFromID(q);q.assemblyNodeId&&n.push(q.assemblyNodeId)}a=this._toStyleTags[a];m=[];if(void 0!==a){for(w=0;w<a.length;w++){var r=this._toStyleVis[a[w]];
q=this._principleStyleSegs[a[w]];if(void 0!==r&&!r.everythingOff()&&void 0!==q)for(r=0;r<q.length;r++){var x=q[r],t=this._hwfParser.getSegmentPropertyManager().getFromID(x);t.assemblyNodeId&&n.push(t.assemblyNodeId)}}for(w=0;w<a.length;w++){var u=this._toStyleMatrix[a[w]];q=this._principleStyleSegs[a[w]];if(void 0!==u&&void 0!==q)for(r=0;r<q.length;r++)if(x=q[r],t=this._hwfParser.getSegmentPropertyManager().getFromID(x),t.assemblyNodeId)for(x=[],this.collectBodyInstance(t.assemblyNodeId,x),t=0;t<
x.length;t++){var p=this._viewer.model.getNodeMatrix(x[t]),v=e.Matrix.createFromArray(u);m.push([x[t],e.Matrix.multiply(p,v)])}}}c=this._viewer.model.createCadView(d,this._captureNames[f],c,n,[],[],m,k,g);null!==c&&"cad_default"===this._captureNames[f]&&(this._viewer.model.activateCadView(c,0),b=!0)}}}return b};a.prototype.collectBodyInstance=function(b,d){this._viewer.model.getNodeType(b)===e.NodeType.BodyInstance&&d.push(b);b=this._viewer.model.getNodeChildren(b);for(var a=0;a<b.length;a++)this.collectBodyInstance(b[a],
d)};a.prototype.addFrame=function(b,d){this._toFrameMeshInstanceData[b]=d};a.prototype.parseCaptureDefinitions=function(b){b=b.split(";");var d=1.91<this._hwfParser.getHwfFileVersionNumber()?5:4;for(var a=0;a<b.length;a+=d){var c=b[a],l=this.parseCamStr(b[a+1]),e=null;if(1.91<this._hwfParser.getHwfFileVersionNumber()){e=this.parseCuttingPlaneStr(b[a+2]);var g=b[a+3];var n=b[a+4].split("&")}else g=b[a+2],n=b[a+3].split("&");this._captureNames.push(c);this._toCaptureTag[c]=g;null!==l&&(this._toCamera[g]=
l);null!==e&&(this._toCuttingPlane[g]=e);this._toStyleTags[g]=n}return b.length/d};a.prototype.parseCaptureStyleDefinitions=function(b){b=b.split(";");for(var d=0;d<b.length;d+=3){var a=b[d],h=c.Visibility.deserialize(b[d+1]);this._toStyleVis[a]=h;h=this.parseMatrix(b[d+2]);null!==h&&(this._toStyleMatrix[a]=h)}};a.prototype.parseDefaultCapture=function(b){};a.prototype.parseCaptureMarkup=function(b,d){};a.prototype.parseCaptureNonStyles=function(b,d){b=b.split(";");for(var a=0;a<b.length;++a){var c=
b[a];this._principleNonStyleSegs.hasOwnProperty(c)||(this._principleNonStyleSegs[c]=[]);this._principleNonStyleSegs[c].push(d)}};a.prototype.parseCaptureStyles=function(b,d){var a=c.Visibility.EMPTY();b=b.split(";");for(var h=0;h<b.length;++h){var l=b[h];this._principleStyleSegs.hasOwnProperty(l)||(this._principleStyleSegs[l]=[]);this._principleStyleSegs[l].push(d);l=this._toStyleVis[l];if(void 0!==l&&!l.empty()){l=l.everythingOff()?c.Visibility.EVERYTHING():c.Visibility.EVERYTHING().not();if(!a.equals(l)&&
!a.empty())throw new e.CommunicatorError("Incompatible style visibilities");a=l}}return a};a.prototype.parseCamStr=function(b){if("?"===b)return null;b=b.split(" ");var d=new e.Camera,a=e.Point3.zero(),c=0;a.x=Number(b[c++]);a.y=Number(b[c++]);a.z=Number(b[c++]);d.setPosition(a);a.x=Number(b[c++]);a.y=Number(b[c++]);a.z=Number(b[c++]);d.setTarget(a);a.x=Number(b[c++]);a.y=Number(b[c++]);a.z=Number(b[c++]);d.setUp(a);d.setWidth(Number(b[c++]));d.setHeight(Number(b[c++]));switch(b[c++]){case "perspective":d.setProjection(e.Projection.Perspective);
break;default:case "orthographic":d.setProjection(e.Projection.Orthographic)}return d};a.prototype.parseCuttingPlaneStr=function(b){if("?"===b)return null;b=b.split(" ");var d=[];d[0]=parseFloat(b[0]);d[1]=parseFloat(b[1]);d[2]=parseFloat(b[2]);d[3]=parseFloat(b[3]);return d};a.prototype.parseMatrix=function(b){if("?"===b)return null;b=b.split("_");for(var d=0;d<b.length;++d)b[d]=Number(b[d]);return b};return a}();c.CaptureParser=p})(v.Internal||(v.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||
(Communicator={}));
(function(e){(function(e){(function(c){(function(c){c.generateLineDataFromPointsAndIndices=function(a,b,d,f,c,l){for(var h=function(b){if(null!==d){var a=new Uint8Array(b.length/3*4);for(var c=0;c<b.length/3;c++){var l=4*c;a[l]=d.r;a[l+1]=d.g;a[l+2]=d.b;a[l+3]=f}}return a},e=function(b,d){b*=3;d.push(a[b]);d.push(a[b+1]);d.push(a[b+2])},n=function(b,d,a){var f=0;void 0!==l&&void 0!==l[m]&&(f=l[m]);a.addPolyline(b,d,f);m++},m=0,w=b.length/2,q=-1,r,x=0;x<w;x++){var t=b[2*x],u=b[2*x+1];t!==q&&(r&&n(r,
h(r),c),r=[],e(t,r));e(u,r);q=u}r&&n(r,h(r),c)};c.generateFaceData=function(a,b,d,f,c,l,e,g,n){for(var h=0;h<b.length;h++){var k=[],q=[],r=[];var x=new Uint8Array(4*b[h].length);for(var t=0;t<b[h].length;t++){var u=b[h][t],p=t,v=q,y=x,B=r,z=3*u;k.push(a[z],a[z+1],a[z+2]);void 0!==d?v.push(d[z],d[z+1],d[z+2]):v.push(0,1,0);v=2*u;c&&B.push(c[v],c[v+1]);u*=3;p*=4;void 0!==f?(y[p]=255*f[u],y[p+1]=255*f[u+1],y[p+2]=255*f[u+2]):(y[p]=l.r,y[p+1]=l.g,y[p+2]=l.b);y[p+3]=e}t=0;void 0!==n&&void 0!==n[h]&&(t=
n[h]);g.addFaces(k,0<q.length?q:void 0,void 0!==x&&0<x.length?x:void 0,0<r.length?r:void 0,t)}}})(c.Data||(c.Data={}))})(e.Internal||(e.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
(function(e){(function(v){(function(c){(function(a){a[a.DoneValue1=0]="DoneValue1";a[a.DoneValue2=1]="DoneValue2";a[a.ColorMap=12]="ColorMap";a[a.PolyPolypoint=16]="PolyPolypoint";a[a.UnicodeOptions=22]="UnicodeOptions";a[a.Matrix=37]="Matrix";a[a.Color=34]="Color";a[a.OpenSegment=40]="OpenSegment";a[a.CloseSegment=41]="CloseSegment";a[a.Comment=59]="Comment";a[a.BoundingType1=66]="BoundingType1";a[a.Heuristics=72]="Heuristics";a[a.FileInfo=73]="FileInfo";a[a.Polypoint=76]="Polypoint";a[a.ClipRegion=
79]="ClipRegion";a[a.Shell=83]="Shell";a[a.UserOptions=85]="UserOptions";a[a.Visibility=86]="Visibility";a[a.Compression=90]="Compression";a[a.BoundingType2=98]="BoundingType2";a[a.Image=105]="Image";a[a.Line=108]="Line";a[a.UserIndexData=109]="UserIndexData";a[a.Tag=113]="Tag";a[a.Reference=114]="Reference";a[a.Texture=116]="Texture";a[a.Camera=125]="Camera";a[a.ColorRgb=126]="ColorRgb";a[a.UserValue=118]="UserValue"})(c.StreamOpcode||(c.StreamOpcode={}));(function(a){a[a.CameraOrtho=0]="CameraOrtho";
a[a.CameraPersp=1]="CameraPersp";a[a.CommentEnd=10]="CommentEnd"})(c.StreamTK||(c.StreamTK={}));(function(a){a[a.Extended=32768]="Extended";a[a.Extras=12]="Extras";a[a.ExtendedMask=4294901760]="ExtendedMask";a[a.ExtendedShift=16]="ExtendedShift"})(c.StreamTKHeuristic||(c.StreamTKHeuristic={}));(function(a){a[a.Bounding=1]="Bounding";a[a.BrepInfo=22]="BrepInfo";a[a.PmiData=23]="PmiData";a[a.Unused1=24]="Unused1";a[a.Unused2=25]="Unused2";a[a.MapId=26]="MapId";a[a.PrototypeMap=27]="PrototypeMap";a[a.SecurityMark=
1802331507]="SecurityMark"})(c.UserIndexData||(c.UserIndexData={}));(function(a){a[a.Cylinder=0]="Cylinder";a[a.Cone=1]="Cone";a[a.Plane=2]="Plane";a[a.Circle=3]="Circle"})(c.BrepType||(c.BrepType={}));(function(a){a[a.EXPANDED=128]="EXPANDED";a[a.FIRSTPASS=16]="FIRSTPASS";a[a.HAS_OPTIONALS=8]="HAS_OPTIONALS"})(c.TKSH||(c.TKSH={}));(function(a){a[a.TKO_Image_RGB=2]="TKO_Image_RGB";a[a.TKO_Image_RGBA=3]="TKO_Image_RGBA";a[a.TKO_Image_JPEG=7]="TKO_Image_JPEG";a[a.TKO_Image_PNG=12]="TKO_Image_PNG";a[a.Format_Mask=
15]="Format_Mask";a[a.Options_Mask=4294967280]="Options_Mask";a[a.Is_Named=128]="Is_Named"})(c.TKO_Image||(c.TKO_Image={}));(function(a){a[a.TERMINATE=0]="TERMINATE";a[a.ALL_NORMALS_POLAR=19]="ALL_NORMALS_POLAR";a[a.FACE_REGIONS=51]="FACE_REGIONS";a[a.ALL_VFINDICES=11]="ALL_VFINDICES";a[a.ALL_PARAMETERS=28]="ALL_PARAMETERS";a[a.ALL_VFCOLORS=5]="ALL_VFCOLORS"})(c.OPT||(c.OPT={}));(function(a){a[a.Diffuse=0]="Diffuse";a[a.Transmission=3]="Transmission"})(c.TKO_Channel||(c.TKO_Channel={}));(function(a){a[a.None=
0]="None";a[a.PNG=5]="PNG"})(c.TKO_Compression||(c.TKO_Compression={}));(function(a){a[a.Extended=128]="Extended";a[a.Extended_Colors=32768]="Extended_Colors";a[a.Extended2=8388608]="Extended2";a[a.Extended_Shift=8]="Extended_Shift";a[a.Extended_Colors_Shift=16]="Extended_Colors_Shift";a[a.Extended2_Shift=24]="Extended2_Shift"})(c.TKO_Geo||(c.TKO_Geo={}));(function(a){a[a.Param_Source=1]="Param_Source";a[a.Tiling=2]="Tiling";a[a.Extended=32768]="Extended";a[a.Extended_Shift=16]="Extended_Shift";a[a.Interpolation=
4]="Interpolation";a[a.Decimation=8]="Decimation";a[a.Param_Offset=262144]="Param_Offset"})(c.TKO_Texture||(c.TKO_Texture={}));(function(a){a[a.COMPRESSED=1]="COMPRESSED";a[a.HAS_EXPLICIT_PRIMITIVE_COUNT=2]="HAS_EXPLICIT_PRIMITIVE_COUNT";a[a.ONE_PRIMITIVE_ONLY=4]="ONE_PRIMITIVE_ONLY";a[a.EXPLICIT_PRIMITIVE_MASK=6]="EXPLICIT_PRIMITIVE_MASK";a[a.GLOBAL_QUANTIZATION=8]="GLOBAL_QUANTIZATION";a[a.ZERO_X=256]="ZERO_X";a[a.SAME_X=512]="SAME_X";a[a.PER_PRIMITIVE_X=768]="PER_PRIMITIVE_X";a[a.ZERO_Y=1024]=
"ZERO_Y";a[a.SAME_Y=2048]="SAME_Y";a[a.PER_PRIMITIVE_Y=3072]="PER_PRIMITIVE_Y";a[a.ZERO_Z=4096]="ZERO_Z";a[a.SAME_Z=8192]="SAME_Z";a[a.PER_PRIMITIVE_Z=12288]="PER_PRIMITIVE_Z";a[a.EXPANDED=32768]="EXPANDED";a[a.X_2D_MASK=768]="X_2D_MASK";a[a.Y_2D_MASK=3072]="Y_2D_MASK";a[a.Z_2D_MASK=12288]="Z_2D_MASK";a[a.ANY_2D_MASK=16128]="ANY_2D_MASK"})(c.TKPP||(c.TKPP={}));(function(a){a[a.UNDEFINED=0]="UNDEFINED";a[a.STRAIGHTLINE=1]="STRAIGHTLINE";a[a.CIRCLE=2]="CIRCLE";a[a.CYLINDER=3]="CYLINDER";a[a.PLANE=4]=
"PLANE";a[a.CONE=5]="CONE";a[a.OTHERLINE=6]="OTHERLINE"})(c.GeometryElementType||(c.GeometryElementType={}));var p=function(){return function(a,b){this.item=a;this.region=b}}();c.RegionInfo=p;p=function(){return function(){this.refsToBrep=[];this.pmiType=e.PmiType.Unknown;this.pmiSubtype=e.PmiSubType.Unknown}}();c.PmiInfo=p})(v.Internal||(v.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
var __awaiter=this&&this.__awaiter||function(e,v,c,p){return new (c||(c=Promise))(function(a,b){function d(d){try{h(p.next(d))}catch(k){b(k)}}function f(d){try{h(p["throw"](d))}catch(k){b(k)}}function h(b){b.done?a(b.value):(new c(function(d){d(b.value)})).then(d,f)}h((p=p.apply(e,v||[])).next())})},__generator=this&&this.__generator||function(e,v){function c(b){return function(d){return p([b,d])}}function p(c){if(b)throw new TypeError("Generator is already executing.");for(;a;)try{if(b=1,d&&(f=c[0]&
2?d["return"]:c[0]?d["throw"]||((f=d["return"])&&f.call(d),0):d.next)&&!(f=f.call(d,c[1])).done)return f;if(d=0,f)c=[c[0]&2,f.value];switch(c[0]){case 0:case 1:f=c;break;case 4:return a.label++,{value:c[1],done:!1};case 5:a.label++;d=c[1];c=[0];continue;case 7:c=a.ops.pop();a.trys.pop();continue;default:if(!(f=a.trys,f=0<f.length&&f[f.length-1])&&(6===c[0]||2===c[0])){a=0;continue}if(3===c[0]&&(!f||c[1]>f[0]&&c[1]<f[3]))a.label=c[1];else if(6===c[0]&&a.label<f[1])a.label=f[1],f=c;else if(f&&a.label<
f[2])a.label=f[2],a.ops.push(c);else{f[2]&&a.ops.pop();a.trys.pop();continue}}c=v.call(e,a)}catch(k){c=[6,k],d=0}finally{b=f=0}if(c[0]&5)throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var a={label:0,sent:function(){if(f[0]&1)throw f[1];return f[1]},trys:[],ops:[]},b,d,f,h;return h={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(h[Symbol.iterator]=function(){return this}),h};
(function(e){(function(v){(function(c){var p=function(){function a(b){this._data=new Uint8Array(0);this._dataView=new DataView(this._data.buffer);this._colorMap=[];this._tagBase=this._currentTag=this._currentBytePosition=0;this._currentlyReadingFrames=this._currentlyParsingMarkup=!1;this._pendingMeshData=[];this._pendingInstanceData=[];this._makingMeshes=!1;this._modelTagToMeshData={};this._currentlyParsingIncludes=!1;this._currentIncludeDepth=0;this._nodeAdditionalIdToSegmentProps={};this._originalFilename=
this._hwfFileVersion="";this._modelUnits=1;this._faceWinding=e.FaceWinding.CounterClockwise;this._segmentPropertyManager=new c.SegmentPropertyManager;this._InstancedDataManager=new c.InstancedDataManager;this._imageResources={};this._textureImageNames={};this._pmiNodeTypeCounter=new Map;this._viewer=b;this._captureParser=new c.CaptureParser(b,this)}a.prototype._log=function(b){console.log(b)};a.prototype.getHwfFileVersion=function(){return this._hwfFileVersion};a.prototype.getHwfFileVersionNumber=
function(){return parseFloat(this._hwfFileVersion)};a.prototype.getOriginalFilename=function(){return this._originalFilename};a.prototype.getModelUnits=function(){return this._modelUnits};a.prototype.getSegmentPropertyManager=function(){return this._segmentPropertyManager};a.prototype.parse=function(b){this._data=new Uint8Array(b);this._dataView=new DataView(this._data.buffer);this._currentBytePosition=0;return this._parseChunk()};a.prototype._parseChunk=function(){return __awaiter(this,void 0,void 0,
function(){var b,d,a,h=this;return __generator(this,function(f){switch(f.label){case 0:if(this._makingMeshes)return[3,32];d=b=this._data[this._currentBytePosition++];switch(d){case c.StreamOpcode.Comment:return[3,1];case c.StreamOpcode.FileInfo:return[3,2];case c.StreamOpcode.BoundingType1:return[3,3];case c.StreamOpcode.BoundingType2:return[3,3];case c.StreamOpcode.Camera:return[3,4];case c.StreamOpcode.UserValue:return[3,5];case c.StreamOpcode.UserIndexData:return[3,6];case c.StreamOpcode.UserOptions:return[3,
7];case c.StreamOpcode.UnicodeOptions:return[3,8];case c.StreamOpcode.Heuristics:return[3,9];case c.StreamOpcode.Visibility:return[3,10];case c.StreamOpcode.OpenSegment:return[3,11];case c.StreamOpcode.Reference:return[3,12];case c.StreamOpcode.Polypoint:return[3,13];case c.StreamOpcode.Line:return[3,14];case c.StreamOpcode.CloseSegment:return[3,15];case c.StreamOpcode.Shell:return[3,16];case c.StreamOpcode.Matrix:return[3,17];case c.StreamOpcode.Tag:return[3,18];case c.StreamOpcode.ColorRgb:return[3,
19];case c.StreamOpcode.PolyPolypoint:return[3,20];case c.StreamOpcode.Color:return[3,21];case c.StreamOpcode.Texture:return[3,22];case c.StreamOpcode.Image:return[3,23];case c.StreamOpcode.ColorMap:return[3,24];case c.StreamOpcode.Compression:return[3,25];case c.StreamOpcode.ClipRegion:return[3,26];case c.StreamOpcode.DoneValue1:return[3,27];case c.StreamOpcode.DoneValue2:return[3,27]}return[3,31];case 1:return this._parseComment(),[3,31];case 2:return this._parseFileInfo(),[3,31];case 3:return this._parseBounding(),
[3,31];case 4:return this._parseCamera(),[3,31];case 5:return this._parseUserValue(),[3,31];case 6:return this._parseUserIndexData(),[3,31];case 7:return this._parseUserOptions(),[3,31];case 8:return this._parseUnicodeOptions(),[3,31];case 9:return this._parseHeuristics(),[3,31];case 10:return this._parseVisibility(),[3,31];case 11:return this._parseOpenSegment(),[3,31];case 12:return this._parseReference(),[3,31];case 13:return this._parsePolyPoint(),[3,31];case 14:return this._parseLine(),[3,31];
case 15:return this._parseCloseSegment(),[3,31];case 16:return this._parseShell(),[3,31];case 17:return this._parseMatrix(),[3,31];case 18:return this._parseTag(),[3,31];case 19:return this._parseColorRgb(),[3,31];case 20:return this._parsePolyPolyPoint(),[3,31];case 21:return this._parseColor(),[3,31];case 22:return this._parseTexture(),[3,31];case 23:return this._parseImage(),[3,31];case 24:return this._parseColorMap(),[3,31];case 25:return this._parseCompression(),[3,31];case 26:return this._parseClipRegion(),
[3,31];case 27:return[4,Promise.all(this._pendingMeshData)];case 28:return f.sent(),[4,Promise.all(this._pendingInstanceData)];case 29:return f.sent(),(a=this._captureParser.exportToModelStructure())||void 0===this._defaultCamera||this._viewer.view.setCamera(this._defaultCamera,0),[4,this._parsingDone()];case 30:return f.sent(),[2];case 31:return[3,0];case 32:return[2,e.Util.sleep(0).then(function(){return h._parseChunk()})]}})})};a.prototype._parseComment=function(){for(;this._data[this._currentBytePosition++]!==
c.StreamTK.CommentEnd;);};a.prototype._parseFileInfo=function(){this._currentBytePosition+=4};a.prototype._parseBounding=function(){0===this._data[this._currentBytePosition++]?this._currentBytePosition+=24:this._currentBytePosition+=16};a.prototype._parseCamera=function(){var b=e.Point3.zero();this._defaultCamera=new e.Camera;var d=this._data[this._currentBytePosition++];this._defaultCamera.setProjection(d===c.StreamTK.CameraOrtho?e.Projection.Orthographic:e.Projection.Perspective);this._readPoint3(b);
this._defaultCamera.setPosition(b);this._readPoint3(b);this._defaultCamera.setTarget(b);this._readPoint3(b);this._defaultCamera.setUp(b);this._defaultCamera.setWidth(this._readFloat());this._defaultCamera.setHeight(this._readFloat());b=this._data[this._currentBytePosition++];this._currentBytePosition+=b};a.prototype._parseUserValue=function(){this._readUnsignedInt()};a.prototype.getHwfRootNode=function(){return this._viewer.model.getAbsoluteRootNode()};a.prototype._parseUserIndexData=function(){for(var b=
this._readInt(),d=this._segmentPropertyManager.current(),a=0,h=0,l=0,k="(null)",g,n,m=0;m<b;m++)0===a&&(h=this._readInt(),a++),1===a&&(l=this._readInt(),a++),2===a&&(h===c.UserIndexData.Bounding?this._readString(l):h===c.UserIndexData.PmiData?this._parsePmiData(l):h===c.UserIndexData.Unused1||h===c.UserIndexData.Unused2?this._currentBytePosition+=l:h===c.UserIndexData.MapId?g=this._readUnsignedInt():h===c.UserIndexData.PrototypeMap?this._parsePrototypeMap():h===c.UserIndexData.BrepInfo?n=this._readString(l):
h===c.UserIndexData.SecurityMark?this._readString(l):(k=c.Util.Utf8.decode(this._readString(l)),k=k.replace(/"/gi," "),this._log("parse assembly name: "+k),d.assemblyTreeName=k),a=0);b=this._viewer.model;void 0!==d.segmentName&&(-1!==d.segmentName.indexOf("part")?(m=d.resolveParentNodeId(b,e.NodeType.AssemblyNode),d.assemblyNodeId=b.createPart(g),b.setPart(m,d.assemblyNodeId),m=parseInt(d.segmentName.split("part ")[1],10),isNaN(m)||(this._nodeAdditionalIdToSegmentProps[m]=d)):-1!==d.segmentName.indexOf("representation item")?
(m=d.resolveParentNodeId(b,e.NodeType.Part),d.assemblyNodeId=b.createAndAddRepresentationItem(m,g),m=parseInt(d.segmentName.split("representation item ")[1],10),isNaN(m)||(this._nodeAdditionalIdToSegmentProps[m]=d)):-1!==d.segmentName.indexOf("product occurrence")&&(m=d.resolveParentNodeId(b,e.NodeType.AssemblyNode),d.assemblyNodeId=b.createNode(m,k,g),m=parseInt(d.segmentName.split("product occurrence ")[1],10),isNaN(m)||(this._nodeAdditionalIdToSegmentProps[m]=d)));void 0!==n&&this._parseBrepInfo(n);
if(void 0!==d.userOptions&&0<d.userOptions.length)for(m=0;m<d.userOptions.length;m++)-1===d.userOptions[m].indexOf("brep_properties")&&-1===d.userOptions[m].indexOf("hx3d_type")&&(n=d.userOptions[m].replace(/`+/g,""),n=n.replace(/\\/g,"sLaSh"),n=n.split("="),k=d.assemblyNodeId?d.assemblyNodeId:this.getHwfRootNode(),b.addPropertyToNode(k,n[0],n[1]));d.brepProperties&&d.assemblyNodeId&&b.getNodeType(d.assemblyNodeId)===e.NodeType.Body&&(k=d.brepProperties.split(" "),m="-1.#IND00"!==k[2]?new e.Point3(parseFloat(k[2]),
parseFloat(k[3]),parseFloat(k[4])):new e.Point3(0,0,0),n=parseFloat(k[0]),k=parseFloat(k[1]),b.setPhysicalProperties(d.assemblyNodeId,m,n,k))};a.prototype._parseUserOptions=function(){var b=this._segmentPropertyManager.current(),d=this._readUnsignedShort();d=this._readString(d);d.indexOf("lights_off");b.userOptions=this._parseUserOptionsString(d);b.brepProperties=c.Util.extractUserOpt(d,"brep_properties");if(this._currentlyParsingMarkup){var a=c.Util.extractUserOpt(d,"pmi_type");a&&b&&(b.pmiInfo=
new c.PmiInfo,"dimension"===a?(b.pmiInfo.pmiType=e.PmiType.Dimension,a=c.Util.extractUserOpt(d,"dimension_subtype"),"distance"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDistance:"distanceoffset"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDistanceOffset:"distancecumulate"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDistanceCumulate:"chamfer"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionChamfer:"slope"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionSlope:"ordinate"===a?b.pmiInfo.pmiSubtype=
e.PmiSubType.DimensionOrdinate:"radius"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionRadius:"radiustangent"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionRadiusTangent:"radiuscylinder"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionRadiusCylinder:"radiusedge"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionRadiusEdge:"diameter"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDiameter:"diametertangent"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDiameterTangent:"diametercylinder"===a?b.pmiInfo.pmiSubtype=
e.PmiSubType.DimensionDiameterCylinder:"diameteredge"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDiameterEdge:"diametercone"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionDiameterCone:"length"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionLength:"lengthcurvilinear"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionLengthCurvilinear:"lengthcircular"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionLengthCircular:"angle"===a&&(b.pmiInfo.pmiSubtype=e.PmiSubType.DimensionAngle)):"note"===a?b.pmiInfo.pmiType=
e.PmiType.Text:"arrow"===a?b.pmiInfo.pmiType=e.PmiType.Arrow:"balloon"===a?b.pmiInfo.pmiType=e.PmiType.Balloon:"balloon"===a?b.pmiInfo.pmiType=e.PmiType.Balloon:"balloon"===a?b.pmiInfo.pmiType=e.PmiType.Balloon:"circlecenter"===a?b.pmiInfo.pmiType=e.PmiType.CircleCenter:"coordinate"===a?b.pmiInfo.pmiType=e.PmiType.Coordinate:"datum"===a?(b.pmiInfo.pmiType=e.PmiType.Datum,a=c.Util.extractUserOpt(d,"datum_type"),"identifier"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.DatumIdent:"target"===a&&(b.pmiInfo.pmiSubtype=
e.PmiSubType.DatumTarget)):"fastener"===a?b.pmiInfo.pmiType=e.PmiType.Fastener:"fcf"===a?(b.pmiInfo.pmiType=e.PmiType.Gdt,b.pmiInfo.pmiSubtype=e.PmiSubType.GdtFcf):"gdt"===a?(b.pmiInfo.pmiType=e.PmiType.Gdt,a=c.Util.extractUserOpt(d,"gdt_subtype"),"fcf"===a&&(b.pmiInfo.pmiSubtype=e.PmiSubType.GdtFcf)):"locator"===a?b.pmiInfo.pmiType=e.PmiType.Locator:"measurementpoint"===a?b.pmiInfo.pmiType=e.PmiType.MeasurementPoint:"roughness"===a?b.pmiInfo.pmiType=e.PmiType.Roughness:"welding"===a?(b.pmiInfo.pmiType=
e.PmiType.Welding,a=c.Util.extractUserOpt(d,"welding_subtype"),"line"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.WeldingLine:"spot"===a&&(b.pmiInfo.pmiSubtype=e.PmiSubType.WeldingSpot)):"table"===a?b.pmiInfo.pmiType=e.PmiType.Table:"other"===a?(b.pmiInfo.pmiType=e.PmiType.Other,a=c.Util.extractUserOpt(d,"other_subtype"),"symboluser"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.OtherSymbolUser:"symbolutility"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.OtherSymbolUtility:"symbolcustom"===a?b.pmiInfo.pmiSubtype=e.PmiSubType.OtherSymbolCustom:
"geometricreference"===a&&(b.pmiInfo.pmiSubtype=e.PmiSubType.OtherGeometricReference)):"generic"===a&&(b.pmiInfo.pmiType=e.PmiType.GeometricalTolerance))}if(a=c.Util.extractUserOpt(d,"prc_hidden"))b.visible=!1;if(a=c.Util.extractUserOpt(d,"default_visibility"))b.visible="off"!==a;a=c.Util.extractUserOpt(d,"hwf_version");null!==a&&(this._hwfFileVersion=a);a=c.Util.extractUserOpt(d,"filename");null!==a&&(this._originalFilename=a,-1!==a.indexOf(".dwg")||-1!==a.indexOf(".dwf")||-1!==a.indexOf(".skp")||
-1!==a.indexOf(".hsf"))&&(this._faceWinding=e.FaceWinding.Unknown);a=c.Util.extractUserOpt(d,"model_units");null!==a&&(this._modelUnits=parseFloat(a));this._captureParser.checkParseCapture(d,b.segmentId)};a.prototype._parseUnicodeOptions=function(){var b=this._readUnsignedShort();this._readString(2*b)};a.prototype._parseHeuristics=function(){var b=this._readUnsignedShort();if(b&c.StreamTKHeuristic.Extended){var a=this._readUnsignedShort();b|=a<<c.StreamTKHeuristic.ExtendedShift}var f=this._readUnsignedShort();
b|c.StreamTKHeuristic.Extended&&(a=this._readUnsignedShort(),f|=a<<c.StreamTKHeuristic.ExtendedShift);0!==(b&f&c.StreamTKHeuristic.Extras)&&(this._readByte(),this._faceWinding=e.FaceWinding.Clockwise)};a.prototype._parseVisibility=function(){var b=this._data[this._currentBytePosition++];this._currentBytePosition++;if(b&c.TKO_Geo.Extended){var a=this._readUnsignedShort();b|=a<<c.TKO_Geo.Extended_Shift}b&c.TKO_Geo.Extended&&(a=this._readUnsignedShort(),b|=a<<c.TKO_Geo.Extended_Shift);b&c.TKO_Geo.Extended2&&
(a=this._readByte(),b|=a<<c.TKO_Geo.Extended2_Shift);b&c.TKO_Geo.Extended2&&this._readByte()};a.prototype._parseOpenSegment=function(){var b=this,a=this._segmentPropertyManager.open(),c=this._data[this._currentBytePosition++];255===c&&(c=this._readUnsignedInt());a.segmentName=this._readString(c);"all_markup"===a.segmentName&&0<this._pendingMeshData.length&&(this._makingMeshes=!0,Promise.all(this._pendingMeshData).then(function(){return Promise.all(b._pendingInstanceData)}).then(function(){b._makingMeshes=
!1;b._pendingMeshData.length=0}));this._currentlyParsingIncludes&&++this._currentIncludeDepth;if("new_includes"===a.segmentName||"zzz_new_includes"===a.segmentName)this._currentlyParsingIncludes=!0,this._log("begin parsing includes");"all_markup"===a.segmentName&&(this._currentlyParsingMarkup=!0);"new_frames"===a.segmentName&&(this._currentlyReadingFrames=!0);this._currentlyParsingIncludes||this._currentlyParsingMarkup||this._currentlyReadingFrames||this._log("Open segment: "+a.segmentName)};a.prototype._parseReference=
function(){var b=this._readUnsignedInt()+this._tagBase;this._readByte();this._modelTagToMeshData.hasOwnProperty(b.toString())?this._segmentPropertyManager.current().geometryReferenceTag=b:this._log("unable to lookup reference: "+b)};a.prototype._parsePolyPoint=function(){var b=this._readUnsignedInt(),a=[];this._readFloatArray(a,3*b);for(var c=[],h=0;h<b;++h)c.push(h);this._addPendingMeshDataToCurrentSegment(!0,[c],a)};a.prototype._parseLine=function(){var b=[];this._readFloatArray(b,6);this._addPendingMeshDataToCurrentSegment(!0,
[[0,1]],b)};a.prototype._registerCurrentMeshDataToTag=function(b,a){this._modelTagToMeshData[b]=a};a.prototype._parseCloseSegment=function(){var b=this,a=this._segmentPropertyManager.close();if(void 0===a)console.assert(!1,"segment closed without opening");else{var c=this._viewer.model,h=new e.Color(200,200,200),l=function(a,d,f,l){a=new e.MeshInstanceData(a);a.setFaceColor(h);a.setMatrix(f);f=d.resolveParentNodeId(c,e.NodeType.AssemblyNode);f=c.createMeshInstance(a,f).then(function(a){d.assemblyNodeId=
a;if(void 0!==l){var f=b._textureImageNames[l];void 0!==f&&(f=b._imageResources[f],void 0!==f&&f.then(function(b){return c.setNodesTexture([a],{imageId:b})}))}return a});b._pendingInstanceData.push(f);return f};this._currentlyParsingIncludes&&(--this._currentIncludeDepth,0===this._currentIncludeDepth&&void 0!==a.meshDataToCreate&&this._registerCurrentMeshDataToTag(this._currentTag,a.meshDataToCreate));if("new_includes"===a.segmentName||"zzz_new_includes"===a.segmentName)this._log("done parsing includes"),
this._currentlyParsingIncludes=!1;"all_markup"===a.segmentName&&(this._currentlyParsingMarkup=!1);"new_frames"===a.segmentName&&(this._currentlyReadingFrames=!1);if(!this._currentlyParsingIncludes&&!this._currentlyParsingMarkup&&!this._currentlyReadingFrames&&(this._log("Close segment: "+a.segmentName),void 0!==a.geometryReferenceTag)){var k=a.geometryReferenceTag,g=a,n=a.resolvePartOrRepItemSegment();void 0!==n&&(g=n);void 0===g.meshDataTagsToCreate&&(g.meshDataTagsToCreate=[]);void 0===g.meshDataTagsAssociatedSegments&&
(g.meshDataTagsAssociatedSegments=[]);g.meshDataTagsToCreate.push(k);g.meshDataTagsAssociatedSegments.push(a)}if(void 0!==a.meshDataTagsToCreate)if(k=this._InstancedDataManager.getRegistrationIndex(a.meshDataTagsToCreate),void 0===k){for(k=0;k<a.meshDataTagsToCreate.length;k++)if(g=this._modelTagToMeshData[a.meshDataTagsToCreate[k]],void 0===g||1>g.length||void 0===a.meshDataTagsAssociatedSegments)console.assert(!1,"internal logic error");else for(void 0===a.meshDataToCreate&&(a.meshDataToCreate=
[]),g[0].segmentDataCameFrom=a.meshDataTagsAssociatedSegments[k],n=0;n<g.length;n++)a.meshDataToCreate.push(g[n]);var m=this._InstancedDataManager.Register(a.meshDataTagsToCreate)}else if(void 0!==a.meshDataTagsAssociatedSegments){var w=a.meshDataTagsAssociatedSegments[0];g=this._InstancedDataManager.registrationIndexToMeshID[k];void 0!==g?l(g,a,w.computeNetMatrix(),w.resolveTextureName()):this._InstancedDataManager.registrationIndexToMeshCreatePromise[k].then(function(d){return __awaiter(b,void 0,
void 0,function(){return __generator(this,function(b){switch(b.label){case 0:return null===d?[3,2]:[4,l(d,a,w.computeNetMatrix(),w.resolveTextureName())];case 1:b.sent(),b.label=2;case 2:return[2]}})})})}else console.assert(!1,"internal logic error");if(void 0!==a.meshDataToCreate){var q=a.meshDataToCreate;if(void 0!==a.resolvePmiInfoSegment())if(void 0===a.pmiInfo)console.assert(!1,"internal logic error");else{var r=a.pmiInfo;k=a.buildMergedMeshData(r.meshData,!0);r.meshData=k;void 0!==k&&(k.setFaceWinding(this._faceWinding),
k.setBackfacesEnabled(!0),this._pendingMeshData.push(c.createMesh(k).then(function(d){var f=e.MeshInstanceCreationFlags.DoNotLight|e.MeshInstanceCreationFlags.DoNotExplode|e.MeshInstanceCreationFlags.DoNotCut|e.MeshInstanceCreationFlags.DoNotOutlineHighlight|e.MeshInstanceCreationFlags.DoNotXRay,l=a.pmiInfo?b._getNextPmiNodeName(a.pmiInfo.pmiType):a.segmentName;f=new e.MeshInstanceData(d,null,l,null,null,null,f);f.setFaceColor(h);l=[];for(var g=0;g<r.refsToBrep.length;g++){var k=r.refsToBrep[g],n=
b._nodeAdditionalIdToSegmentProps[k.item];if(void 0!==n&&(n=n.resolveParentNodeId(c,e.NodeType.BodyInstance),void 0!==n)){var m=new e.RefOnTopoItem;m.bodyId=n;m.subElementType=e.PmiTopoRef.Face;m.subElementIndex=k.region;l.push(m)}}b._pendingInstanceData.push(c.createPmiInstance(f,r.pmiType,r.pmiSubtype,l,a.resolveParentNodeId(c,e.NodeType.AssemblyNode)).then(function(b){return a.assemblyNodeId=b}));return d})))}else this._currentlyParsingIncludes||(k=a.buildMergedMeshData(void 0,!1),void 0!==k&&
(k.setManifold(!0),k.setFaceWinding(this._faceWinding),k.setBackfacesEnabled(!1),this._pendingMeshData.push(c.createMesh(k).then(function(d){void 0!==m&&(b._InstancedDataManager.registrationIndexToMeshID[m]=d);var c=q[0].segmentDataCameFrom;l(d,a,c.computeNetMatrix(),c.resolveTextureName());return d})),void 0!==m&&(this._InstancedDataManager.registrationIndexToMeshCreatePromise[m]=this._pendingMeshData[this._pendingMeshData.length-1])))}}};a.prototype._getNextPmiNodeName=function(b){var a=this._pmiNodeTypeCounter.has(b)?
this._pmiNodeTypeCounter.get(b):0;a+=1;this._pmiNodeTypeCounter.set(b,a);return e.Internal.Tree.PmiType[b]+"."+a};a.prototype._parseShell=function(){var b=this._readByte();b&c.TKSH.EXPANDED&&this._readUnsignedShort();b&c.TKSH.FIRSTPASS||this._readUnsignedInt();this._readByte();var a=this._readUnsignedInt(),f=[];this._readFloatArray(f,3*a);this._readByte();var h=this._readUnsignedInt();var l=this._readByte();var k=[],g=0;32===l?(g=(h-1)/4,this._readIntArray(k,g)):16===l?(g=(h-1)/2,this._readUnsignedShortArray(k,
g)):8===l&&(g=h-1,this._readByteArray(k,g));var n;h=!1;var m=[];if(b&c.TKSH.HAS_OPTIONALS)for(n=[];b=this._readByte(),b!==c.OPT.TERMINATE;)if(b===c.OPT.ALL_NORMALS_POLAR)b=[],this._readFloatArray(b,2*a),c.Util.normalsPolarToCartesian(a,b,n);else if(b===c.OPT.ALL_PARAMETERS){b=this._readByte();l=b*a;var w=[];3<=b?this._parseUVPairsFromTriples(w,l,b):this._readFloatArray(w,l)}else if(b===c.OPT.ALL_VFINDICES){this._readByte();l=[];this._readFloatArray(l,6);var q=this._readByte(),r=this._readUnsignedInt();
b=[];var p=[];this._readIntArray(b,r/4);c.Util.unquantizeAndUnpackFloats(a,1,q,l,b,p)}else if(b===c.OPT.ALL_VFCOLORS)h=!0,this._readByte(),l=this._readByte(),q=this._readUnsignedInt(),b=[],p=[],this._readByteArray(b,q),c.Util.unquantizeAndUnpackFloats(a,3,l,[0,0,0,1,1,1],b,p);else if(b===c.OPT.FACE_REGIONS){b=0;l=this._readByte();if(0!==(l&3))switch(l&24){case 0:b=this._readInt();break;case 8:b=this._readByte();break;case 16:b=this._readUnsignedShort()}switch(l&3){case 0:for(q=b=0;b<g;)r=0<k[b]?k[b]:
-k[b],q+=r-2,b+=r+1;b=q;break;case 2:++b;break;case 3:b*=2}b*=4;q=[];r=b/4;switch(l&24){case 0:this._readIntArray(q,r);break;case 8:this._readByteArray(q,r);break;case 16:this._readUnsignedShortArray(q,r)}r=b/4;switch(l&3){case 0:for(b=0;b<r;b++)m[b]=q[b];break;case 3:for(b=l=0;b<r;b+=2)for(var t=0;t<q[b+1];t++)m[l++]=q[b]}}t=r=0;var u=[0,0,0],v=0,A=0;l=[];if(0<m.length){for(b=q=0;b<m.length;++b)q<m[b]+1&&(q=m[b]+1);for(b=0;b<q;++b)l.push([])}for(b=0;b<g;++b)switch(r){case 0:0===m.length&&l.push([]);
t=k[b];0<t&&(r=1);break;case 1:u[0]=k[b];--t;r=0===t?0:2;break;case 2:u[1]=k[b];--t;r=0===t?0:3;break;case 3:u[2]=k[b];0===m.length?l[l.length-1].push(u[0],u[1],u[2]):l[m[A]].push(u[0],u[1],u[2]);--t;r=0===t?0:4;v=1;A++;break;case 4:u[0]=u[1],u[1]=u[2],u[2]=k[b],0===m.length?1===v?l[l.length-1].push(u[2],u[1],u[0]):l[l.length-1].push(u[0],u[1],u[2]):1===v?l[m[A]].push(u[2],u[1],u[0]):l[m[A]].push(u[0],u[1],u[2]),v=-v,--t,0===t&&(r=0),A++}if(void 0!==p){var y=[];if(h)for(b=0;b<a;b++)y[3*b]=p[3*b],
y[3*b+1]=p[3*b+1],y[3*b+2]=p[3*b+2];else for(b=0;b<a;b++)g=Math.floor(p[b]),h=Math.ceil(p[b]),k=h-p[b],g=new e.Point3(this._colorMap[3*g],this._colorMap[3*g+1],this._colorMap[3*g+2]),h=new e.Point3(this._colorMap[3*h],this._colorMap[3*h+1],this._colorMap[3*h+2]),h=new e.Point3(h.x-g.x,h.y-g.y,h.z-g.z),y[3*b]=g.x+k*h.x,y[3*b+1]=g.y+k*h.y,y[3*b+2]=g.z+k*h.z}this._addPendingMeshDataToCurrentSegment(!1,l,f,n,w,y)};a.prototype._addPendingMeshDataToCurrentSegment=function(b,a,c,h,e,k){var d=this._segmentPropertyManager.current();
if(this._currentlyParsingMarkup){var f=d.resolvePmiInfoSegment();void 0!==f&&(d=f)}else f=d.resolvePartOrRepItemSegment(),void 0!==f&&(d=f);b={indices:a,points:c,wireframe:b,segmentDataCameFrom:this._segmentPropertyManager.current()};null!==h&&(b.normals=h);null!==e&&(b.uvs=e);null!==k&&(b.vertexColors=k);void 0===d.meshDataToCreate&&(d.meshDataToCreate=[]);d.meshDataToCreate.push(b)};a.prototype._parseMatrix=function(){var a=new e.Matrix;a.m[0]=this._readFloat();a.m[1]=this._readFloat();a.m[2]=this._readFloat();
a.m[3]=0;a.m[4]=this._readFloat();a.m[5]=this._readFloat();a.m[6]=this._readFloat();a.m[7]=0;a.m[8]=this._readFloat();a.m[9]=this._readFloat();a.m[10]=this._readFloat();a.m[11]=0;a.m[12]=this._readFloat();a.m[13]=this._readFloat();a.m[14]=this._readFloat();a.m[15]=1;this._segmentPropertyManager.current().matrix=a};a.prototype._parseTag=function(){this._currentTag++};a.prototype._parseColorRgb=function(){var a=this._readByte();if(0!==(a&c.TKO_Geo.Extended)){var d=this._readByte();a|=d<<c.TKO_Geo.Extended_Shift}0!==
(a&c.TKO_Geo.Extended_Colors)&&(d=this._readByte(),a|=d<<c.TKO_Geo.Extended_Colors_Shift);0!==(a&c.TKO_Geo.Extended2)&&this._readByte();a=[];this._readByteArray(a,3);this._segmentPropertyManager.current().color=new e.Color(a[0],a[1],a[2])};a.prototype._parsePolyPolyPoint=function(){var a=this,d=this._readUnsignedShort(),f=0,h=this._readUnsignedInt();d&c.TKPP.EXPLICIT_PRIMITIVE_MASK&&(d&c.TKPP.ONE_PRIMITIVE_ONLY?f=1:d&c.TKPP.HAS_EXPLICIT_PRIMITIVE_COUNT&&(f=this._readInt()));var l=[];if(d&c.TKPP.EXPLICIT_PRIMITIVE_MASK)this._readIntArray(l,
f);else{for(var k=0;k<h;)l[f]=this._readUnsignedInt(),k+=l[f],f++;this._currentTag+=f-1}var g=c.Util.figureNumFromFloats(d,f,h);if(0!==g){k=[];this._readFloatArray(k,g);d&c.TKPP.ANY_2D_MASK&&(g=[],c.Util.unmangleFloats(h,k,f,l,d,g),k=g);d=[];for(g=h=0;g<f;g++){for(var n=0;n<l[g]-1;n++)d.push(h,h+1),h++;h++}if(this._currentlyReadingFrames){f=new e.MeshData;c.Data.generateLineDataFromPointsAndIndices(k,d,null,255,f,void 0);var m=this._segmentPropertyManager.current();this._viewer.model.createMesh(f).then(function(b){b=
new e.MeshInstanceData(b,null,null,null,null,null,e.MeshInstanceCreationFlags.DoNotSelect|e.MeshInstanceCreationFlags.DoNotExplode|e.MeshInstanceCreationFlags.DoNotCut|e.MeshInstanceCreationFlags.DoNotXRay);b.setMatrix(m.computeNetMatrix());var d=m.resolveColor();void 0!==d&&b.setLineColor(d);d=m.resolveName();void 0!==d&&a._captureParser.addFrame(d,b)})}else this._addPendingMeshDataToCurrentSegment(!0,[d],k)}};a.prototype._parseColor=function(){var a=this._readByte();if(0!==(a&c.TKO_Geo.Extended)){var d=
this._readByte();a|=d<<c.TKO_Geo.Extended_Shift}0!==(a&c.TKO_Geo.Extended_Colors)&&(d=this._readByte(),a|=d<<c.TKO_Geo.Extended_Colors_Shift);0!==(a&c.TKO_Geo.Extended2)&&this._readByte();a=this._readByte();d=0;0!==(a&1<<c.TKO_Channel.Diffuse)&&(d=this._readByte());if(0!==(a&1<<c.TKO_Channel.Diffuse))if(0!==d)if(d=this._readString(d),-1!==d.indexOf("r=")){if(d=/r=([\.\d]*) g=([\.\d]*) b=([\.\d]*) (\w*)/.exec(d),null!==d){var f=this._segmentPropertyManager.current();f.color=e.Color.createFromFloat(parseFloat(d[1]),
parseFloat(d[2]),parseFloat(d[3]));f.textureName=d[4]}}else this._segmentPropertyManager.current().color=e.Color.white();else d=[],this._readByteArray(d,3),this._segmentPropertyManager.current().color=new e.Color(d[0],d[1],d[2]);0!==(a&1<<c.TKO_Channel.Transmission)&&this._readByte();0!==(a&1<<c.TKO_Channel.Transmission)&&(a=[],this._readByteArray(a,3),0!==a[0]&&(this._segmentPropertyManager.current().transparency=255-a[0]))};a.prototype._parseTexture=function(){var a=this._data[this._currentBytePosition++];
255===a&&(a=this._readUnsignedInt());var d=this._readString(a);a=this._data[this._currentBytePosition++];255===a&&(a=this._readUnsignedInt());a=this._readString(a);var f=this._readUnsignedShort();if(0!==(f&c.TKO_Texture.Extended)){var h=this._readUnsignedShort();f|=h<<c.TKO_Texture.Extended_Shift}0!==(f&c.TKO_Texture.Param_Source)&&this._readByte();0!==(f&c.TKO_Texture.Tiling)&&this._readByte();0!==(f&c.TKO_Texture.Interpolation)&&this._readByte();0!==(f&c.TKO_Texture.Decimation)&&this._readByte();
0!==(f&c.TKO_Texture.Param_Offset)&&this._readByte();this._textureImageNames[d]=a};a.prototype._parseImage=function(){var a=e.Point3.zero();this._readPoint3(a);var d=this._readUnsignedInt();a=d&c.TKO_Image.Format_Mask;d&=c.TKO_Image.Options_Mask;var f=0;0!==(d&c.TKO_Image.Is_Named)&&(f=this._data[this._currentBytePosition++],255===f&&(f=this._readUnsignedInt()));var h="";0!==(d&c.TKO_Image.Is_Named)&&(h=this._readString(f));f=e.Point2.zero();f.x=this._readUnsignedInt();f.y=this._readUnsignedInt();
d=this._data[this._currentBytePosition++];var l=d===c.TKO_Compression.None?f.x*f.y:this._readUnsignedInt();var k=new Uint8Array(l);this._readByteArray(k,l);if(d===c.TKO_Compression.None){l*=4;for(var g=new Uint8Array(l),n=0,m=0;m<l;m+=4)g[m]=k[n],g[m+1]=k[n],g[m+2]=k[n],g[m+3]=1,n++;k=g;l=e.ImageFormat.Rgba32}else l=e.ImageFormat.Jpeg;f=this._viewer.model.createImage({format:l,data:k,width:f.x,height:f.y});this._imageResources[h]=f;a!==c.TKO_Image.TKO_Image_JPEG&&d!==c.TKO_Compression.None&&(0!==
this._readByte()?(a=this._readUnsignedInt(),h=new Uint8Array(a),this._readByteArray(h,a)):this._readByte())};a.prototype._parseColorMap=function(){var a=this._readByte(),d=this._readInt();0===a&&this._readFloatArray(this._colorMap,3*d)};a.prototype._parseCompression=function(){var a=this._data.subarray(this._currentBytePosition);this._data=jz.zlib.decompress(a);this._dataView=new DataView(this._data.buffer);this._currentBytePosition=0};a.prototype._parseClipRegion=function(){this._readByte();var a=
this._readInt();this._readFloatArray([],a)};a.prototype._parsingDone=function(){return __awaiter(this,void 0,void 0,function(){var a,d,c,h,l;return __generator(this,function(b){switch(b.label){case 0:return this._log("parsing complete!"),a=this._viewer.model,[4,a._hwfAwaitAssemblyTreeReady()];case 1:return b.sent(),d=this._viewer._getCallbackManager(),c=e.Internal.AttachType.Indirect,[4,d.promiseTrigger("_firstAttachment",null,c)];case 2:return b.sent(),[4,d.promiseTrigger("_firstBoundingReady",null)];
case 3:return b.sent(),h=a.getAbsoluteRootNode(),l=a.getNodeChildren(h),[4,d.promiseTrigger("_firstModelLoaded","firstModelLoaded",l,!0,c)];case 4:return b.sent(),d.trigger("hwfParseComplete"),[2]}})})};a.prototype._readByte=function(){return this._data[this._currentBytePosition++]};a.prototype._readPoint3=function(a){a.x=this._dataView.getFloat32(this._currentBytePosition,!0);this._currentBytePosition+=4;a.y=this._dataView.getFloat32(this._currentBytePosition,!0);this._currentBytePosition+=4;a.z=
this._dataView.getFloat32(this._currentBytePosition,!0);this._currentBytePosition+=4};a.prototype._readFloat=function(){var a=this._dataView.getFloat32(this._currentBytePosition,!0);this._currentBytePosition+=4;return a};a.prototype._readUnsignedInt=function(){var a=this._dataView.getUint32(this._currentBytePosition,!0);this._currentBytePosition+=4;return a};a.prototype._readUnsignedShort=function(){var a=this._dataView.getUint16(this._currentBytePosition,!0);this._currentBytePosition+=2;return a};
a.prototype._readString=function(a){for(var b="",c=0;c<a;c++){var h=this._data[this._currentBytePosition++];0<h&&(b+=String.fromCharCode(h))}return b};a.prototype._parsePmiData=function(a){a=this._readString(a).split(",");for(var b=0;b<a.length&&""!==a[b];b++){var f=a[b].split(" ");f=new c.RegionInfo(parseInt(f[0],10),parseInt(f[1],10));var h=this._segmentPropertyManager.current().resolvePmiInfoSegment();void 0!==h&&void 0!==h.pmiInfo&&h.pmiInfo.refsToBrep.push(f)}};a.prototype._parsePrototypeMap=
function(){for(var a=this._readUnsignedInt(),d=0;d<a;d++){var c=this._readUnsignedInt();if(0===c)break;this._readUnsignedInt();for(var h=0;h<c;h++)this._readUnsignedInt()}for(d=0;d<a;d++){c=this._readUnsignedInt();if(0===c)break;this._readUnsignedInt();for(h=0;h<c;h++)this._readUnsignedInt()}};a.prototype._parseBrepInfo=function(a){var b=this._viewer.model,f=this._segmentPropertyManager.current(),h=f.resolveParentNodeId(b,e.NodeType.Body);if(void 0===h)console.assert(!1,"internal logic error");else{a=
a.split(",");if(0<a.length&&(f=f.resolvePartOrRepItemSegment())){f.measurementBitsOnEdge=[];f.measurementBitsOnFace=[];var l=f.measurementBitsOnEdge;var k=f.measurementBitsOnFace}for(f=0;f<a.length;f++)if(0!==a[f].length){var g=a[f].split(" "),n=parseInt(g[0],10),m=parseInt(g[1],10);if(m===c.GeometryElementType.CYLINDER){var p=parseFloat(g[2]),q=new e.Point3(parseFloat(g[3]),parseFloat(g[4]),parseFloat(g[5]));m=new e.Point3(parseFloat(g[6]),parseFloat(g[7]),parseFloat(g[8]));g=new e.SubentityProperties.CylinderElement(p,
q,m);b.setFaceProperty(h,n,g);k&&(k[n]=1)}else m===c.GeometryElementType.PLANE?(p=new e.Point3(parseFloat(g[2]),parseFloat(g[3]),parseFloat(g[4])),m=new e.Point3(parseFloat(g[5]),parseFloat(g[6]),parseFloat(g[7])),g=new e.SubentityProperties.PlaneElement(p,m),b.setFaceProperty(h,n,g),k&&(k[n]=3)):m===c.GeometryElementType.CONE?(p=parseFloat(g[2]),q=new e.Point3(parseFloat(g[3]),parseFloat(g[4]),parseFloat(g[5])),m=new e.Point3(parseFloat(g[6]),parseFloat(g[7]),parseFloat(g[8])),g=parseFloat(g[9]),
g=new e.SubentityProperties.ConeElement(p,q,m,g),b.setFaceProperty(h,n,g),k&&(k[n]=1)):(m===c.GeometryElementType.CIRCLE?(p=parseFloat(g[2]),q=new e.Point3(parseFloat(g[3]),parseFloat(g[4]),parseFloat(g[5])),m=new e.Point3(parseFloat(g[6]),parseFloat(g[7]),parseFloat(g[8])),g=new e.SubentityProperties.CircleElement(p,q,m),b.setEdgeProperty(h,n,g)):(void 0!==g[2]?(g=parseFloat(g[2]),g=new e.SubentityProperties.LineElement(g)):g=new e.SubentityProperties.LineElement(-1),b.setEdgeProperty(h,n,g)),l&&
(l[n]=4))}}};a.prototype._parseUserOptionsString=function(a){a=a.split(",");for(var b=[],f=0;f<a.length;f++){var h=a[f];-1===h.indexOf("brep_properties")&&-1===h.indexOf("hx3d_type")&&(h=c.Util.Utf8.decode(h.replace(/`+/g,"")).replace(/\\/g,"/"),b.push(h))}return b};a.prototype._readByteArray=function(a,d){for(var b=0;b<d;b++)a[b]=this._readByte()};a.prototype._readFloatArray=function(a,d){for(var b=0;b<d;b++)a.push(this._readFloat())};a.prototype._readIntArray=function(a,d){for(var b=0;b<d;b++)a.push(this._readInt())};
a.prototype._readUnsignedShortArray=function(a,d){for(var b=0;b<d;b++)a.push(this._readUnsignedShort())};a.prototype._readInt=function(){var a=this._dataView.getInt32(this._currentBytePosition,!0);this._currentBytePosition+=4;return a};a.prototype._parseUVPairsFromTriples=function(a,d,c){for(var b=0;b<d;b+=c)a.push(this._readFloat()),a.push(this._readFloat()),this._currentBytePosition+=4*(c-2)};return a}();c.HWFParser=p})(v.Internal||(v.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator=
{}));
(function(e){(function(v){var c=function(){function c(a){this._viewer=a}c.prototype.import=function(a){var b=this,d=e.Internal.OpenPromise.create(),c=new XMLHttpRequest;c.open("GET",a.url,!0);c.responseType="arraybuffer";a.XHRonprogress&&(c.onprogress=a.XHRonprogress);a.XHRonerror&&(c.onerror=a.XHRonerror);if(a.XHRonloadend){var h=a.XHRonloadend;c.onloadend=function(a){h(a,c.status)}}c.onreadystatechange=function(){return __awaiter(b,void 0,void 0,function(){return __generator(this,function(a){switch(a.label){case 0:if(4!==c.readyState)return[3,
3];if(404!==c.status)return[3,1];d.reject(new e.LoadError("Failed to import HWF file."));return[3,3];case 1:return[4,this._fileLoadSucess(c.response)];case 2:a.sent(),this._prepareViewer(),d.resolve(),a.label=3;case 3:return[2]}})})};c.send(null);return d};c.prototype._fileLoadSucess=function(a){return(new v.Internal.HWFParser(this._viewer)).parse(a)};c.prototype._prepareViewer=function(){this._viewer.operatorManager.getOperator(e.OperatorId.MeasureFaceFaceAngle).setUseAuthoredNormals(!1)};return c}();
v.Importer=c})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
(function(e){(function(e){(function(c){var e=Promise.resolve(null),a=function(){function a(){this.tagsOfAlreadyCreatedMergedMesh=[];this.registrationIndexToMeshCreatePromise=[];this.registrationIndexToMeshID=[]}a.prototype.Register=function(a){this.registrationIndexToMeshCreatePromise.push(e);this.registrationIndexToMeshID.push(void 0);return this.tagsOfAlreadyCreatedMergedMesh.push(a)-1};a.prototype.getRegistrationIndex=function(a){for(var b=0;b<this.tagsOfAlreadyCreatedMergedMesh.length;b++){var d=
this.tagsOfAlreadyCreatedMergedMesh[b],c=!0;d.length!==a.length&&(c=!1);for(var e=0;c&&e<d.length;e++)c=-1!==a.indexOf(d[e]);if(c)return b}};return a}();c.InstancedDataManager=a})(e.Internal||(e.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));(function(e){(function(e){var c=function(){return function(){this.url=""}}();e.ImportOptions=c})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
(function(e){(function(v){(function(c){var p=function(){function a(a,b){this.children=[];this.visible=!0;this.parent=a;this.segmentId=b;a&&a.children.push(this)}a.prototype.resolveParentNodeId=function(a,b){var d=this;do{if(d.assemblyNodeId&&a.getNodeType(d.assemblyNodeId)===b)return d.assemblyNodeId;d=d.parent}while(d)};a.prototype.resolveColor=function(){var a=this;do{if(void 0!==a.color)return a.color;a=a.parent}while(a)};a.prototype.resolveTransparency=function(){var a=this;do{if(void 0!==a.transparency)return a.transparency;
a=a.parent}while(a);return 255};a.prototype.resolveTextureName=function(){var a=this;do{if(void 0!==a.textureName)return a.textureName;a=a.parent}while(a)};a.prototype.resolveName=function(){var a=this;do{if(void 0!==a.segmentName&&0<a.segmentName.length)return a.segmentName;a=a.parent}while(a)};a.prototype.resolveMatrix=function(){var a=this;do{if(void 0!==a.matrix)return a.matrix;a=a.parent}while(a)};a.prototype.resolvePmiInfoSegment=function(){var a=this;do{if(void 0!==a.pmiInfo)return a;a=a.parent}while(a)};
a.prototype.resolvePartOrRepItemSegment=function(){var a=this;do{if(void 0!==a.segmentName&&(-1!==a.segmentName.indexOf("part")||-1!==a.segmentName.indexOf("representation item")))return a;a=a.parent}while(a)};a.prototype.computeNetMatrix=function(){for(var a=new e.Matrix,b=this;null!==b;)void 0!==b.matrix&&(a=e.Matrix.multiply(a,b.matrix)),b=b.parent;return a};a.prototype.buildMergedMeshData=function(a,b){if(void 0===this.meshDataToCreate)return a;for(var d=0;d<this.meshDataToCreate.length;d++){var f=
this.meshDataToCreate[d],k=f.points,g=f.normals,n=f.indices,m=f.vertexColors,p=f.uvs,q=f.segmentDataCameFrom.resolveTransparency(),r=f.segmentDataCameFrom.resolveColor();void 0===r&&(r=new e.Color(192,192,192));var v=f.segmentDataCameFrom.computeNetMatrix();if(b){f=new e.Point3(0,0,0);for(var t=0;t<k.length;t+=3)f.set(k[t],k[t+1],k[t+2]),v.transform(f,f),k[t]=f.x,k[t+1]=f.y,k[t+2]=f.z;if(void 0!==g)for(v=v.normalMatrix(),t=0;t<g.length;t+=3)f.set(g[t],g[t+1],g[t+2]),null!==v&&v.transform(f,f),f.normalize(),
g[t]=f.x,g[t+1]=f.y,g[t+2]=f.z}void 0===a&&(a=new e.MeshData);this.meshDataToCreate[d].wireframe?c.Data.generateLineDataFromPointsAndIndices(k,n[0],r,q,a,this.measurementBitsOnEdge):c.Data.generateFaceData(k,n,g,m,p,r,q,a,this.measurementBitsOnFace)}return a};return a}();c.SegmentProperty=p;var a=function(){function a(){this._segmentStack=[];this._allSegments=[];this._idToSegmentMap={};this._segmentIDGenerator=0}a.prototype.open=function(){var a=null;0<this._segmentStack.length&&(a=this._segmentStack[this._segmentStack.length-
1]);a=new p(a,this._segmentIDGenerator++);this._segmentStack.push(a);this._idToSegmentMap[a.segmentId]=a;this._allSegments.push(a);return a};a.prototype.close=function(){return this._segmentStack.pop()};a.prototype.current=function(){return 0<this._segmentStack.length?this._segmentStack[this._segmentStack.length-1]:this.open()};a.prototype.getFromID=function(a){return this._idToSegmentMap[a]};a.prototype.getSegments=function(){return this._allSegments};return a}();c.SegmentPropertyManager=a})(v.Internal||
(v.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
(function(e){(function(e){(function(c){(function(e){function a(a,c,f,e){var b=1/255,d=[e[0],e[1],e[2]];b=[(e[3]-d[0])*b,(e[4]-d[1])*b,(e[5]-d[2])*b];for(var g=0,h=0;a--;)f[0+g]=255===c[0+h]?e[3]:c[0+h]*b[0]+d[0],f[1+g]=255===c[1+h]?e[4]:c[1+h]*b[1]+d[1],f[2+g]=255===c[2+h]?e[5]:c[2+h]*b[2]+d[2],g+=3,h+=3}(function(a){a.decode=function(a){for(var b="",c=0,d,e,g;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(e=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|e&63),
c+=2):(e=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(e&63)<<6|g&63),c+=3);return b}})(e.Utf8||(e.Utf8={}));e.capitaliseFirst=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};e.extractUserOpt=function(a,c){var b=a.indexOf(c+"=");return 0<=b?(a=a.substr(b+c.length+1),b=a.indexOf(","),0<=b&&(a=a.substr(0,b)),a):null};e.normalsPolarToCartesian=function(a,c,e){for(var b=0;b<a;b++){var d=c[2*b],f=c[2*b+1],g=Math.sin(f);e[3*b]=g*Math.cos(d);e[3*b+1]=Math.cos(f);e[3*b+
2]=g*Math.sin(d)}};e.unquantizeAndUnpackFloats=function(b,d,e,h,l,k){var f=[],n=new c.BPack;if(8===e&&3===d)a(b,l,k,h);else{for(var m=(1<<e)-1,p=1/m,q=0;q<d;q++)f[q]=(h[d+q]-h[q])*p;n.InitRead(l);for(l=0;b--;){for(q=0;q<d;q++)p=n.Get(e),k[q+l]=p!==m?p*f[q]+h[q]:h[q+d];l+=d}}};e.trivialDecompressPoints=a;e.figureNumDimensions=function(a){var b=0;a&c.TKPP.X_2D_MASK||b++;a&c.TKPP.Y_2D_MASK||b++;a&c.TKPP.Z_2D_MASK||b++;return b};e.figureNumFromFloats=function(a,d,e){var b=0;if(0===d)return 0;switch(a&
c.TKPP.X_2D_MASK){case c.TKPP.SAME_X:++b;break;case c.TKPP.PER_PRIMITIVE_X:b+=d;break;case 0:b+=e}switch(a&c.TKPP.Y_2D_MASK){case c.TKPP.SAME_Y:++b;break;case c.TKPP.PER_PRIMITIVE_Y:b+=d;break;case 0:b+=e}switch(a&c.TKPP.Z_2D_MASK){case c.TKPP.SAME_Z:++b;break;case c.TKPP.PER_PRIMITIVE_Z:b+=d;break;case 0:b+=e}return b};e.unmangleFloats=function(a,d,e,h,l,k){for(var b=0,f=0;f<a;f++)l&c.TKPP.X_2D_MASK||(k[3*f]=d[b++]),l&c.TKPP.Y_2D_MASK||(k[3*f+1]=d[b++]),l&c.TKPP.Z_2D_MASK||(k[3*f+2]=d[b++]);if(l&
c.TKPP.X_2D_MASK){var m=0;if((l&c.TKPP.X_2D_MASK)===c.TKPP.PER_PRIMITIVE_X)for(f=0;f<e;f++){for(var p=0;p<h[f];p++)k[m]=d[b],m+=3;b++}else if((l&c.TKPP.X_2D_MASK)===c.TKPP.SAME_X){for(f=0;f<a;f++)k[m]=d[b],m+=3;b++}else if((l&c.TKPP.X_2D_MASK)===c.TKPP.ZERO_X)for(f=0;f<a;f++)k[m]=0,m+=3}if(l&c.TKPP.Y_2D_MASK)if(m=1,(l&c.TKPP.Y_2D_MASK)===c.TKPP.PER_PRIMITIVE_Y)for(f=0;f<e;f++){for(p=0;p<h[f];p++)k[m]=d[b],m+=3;b++}else if((l&c.TKPP.Y_2D_MASK)===c.TKPP.SAME_Y){for(f=0;f<a;f++)k[m]=d[b],m+=3;b++}else if((l&
c.TKPP.Y_2D_MASK)===c.TKPP.ZERO_Y)for(f=0;f<a;f++)k[m]=0,m+=3;if(l&c.TKPP.Z_2D_MASK)if(m=2,(l&c.TKPP.Z_2D_MASK)===c.TKPP.PER_PRIMITIVE_Z)for(f=0;f<e;f++){for(p=0;p<h[f];p++)k[m]=d[b],m+=3;b++}else if((l&c.TKPP.Z_2D_MASK)===c.TKPP.SAME_Z)for(f=0;f<a;f++)k[m]=d[b],m+=3;else if((l&c.TKPP.Z_2D_MASK)===c.TKPP.ZERO_Z)for(f=0;f<a;f++)k[m]=0,m+=3}})(c.Util||(c.Util={}))})(e.Internal||(e.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||(Communicator={}));
(function(e){(function(e){(function(c){var e=function(){return function(){}}();c.VisibilitySettings=e;var a=function(){function a(a){this._settings=new e;void 0!==a&&(this._settings[a]=!0)}a.EMPTY=function(){return new a};a.EVERYTHING=function(){return new a("everything")};a.GEOMETRY=function(){return new a("geometry")};a.FACES=function(){return new a("faces")};a.LINES=function(){return new a("lines")};a.TEXT=function(){return new a("text")};a.deserialize=function(b){var c=new a;b=b.split("");c._settings.everything=
c.deserialize_(b);c._settings.geometry=c.deserialize_(b);c.skipToNextGrouping(b);c._settings.faces=c.deserialize_(b);c._settings.lines=c.deserialize_(b);c._settings.text=c.deserialize_(b);return c};a.prototype.skipToNextGrouping=function(a){for(;"-"!==a[0];)a.shift();a.shift()};a.prototype.deserialize_=function(a){a=a.shift();if("1"===a)return!0;if("0"===a)return!1};a.prototype.everythingOn=function(){return this.equals(a.EVERYTHING())};a.prototype.everythingOff=function(){return this.equals(a.EVERYTHING().not())};
a.prototype.empty=function(){return this.equals(a.EMPTY())};a.prototype.not=function(){for(var b=new a,c=0;c<a.allSettings.length;++c){var e=a.allSettings[c];b._settings[e]=this.not_(this._settings[e])}return b};a.prototype.not_=function(a){if(!0===a)return!1;if(!1===a)return!0};a.prototype.toHoopsStr=function(){var a=""+this.toStr("everything");a+=this.toStr("geometry");a+=this.toStr("faces");a+=this.toStr("lines");return a+=this.toStr("text")};a.prototype.toStr=function(a){return!0===this._settings[a]?
a.substr(1)+"=on":!1===this._settings[a]?a.substr(1)+"=off":""};a.prototype.toString=function(){return this.toHoopsStr()};a.prototype.equals=function(b){for(var c=0;c<a.allSettings.length;++c){var d=a.allSettings[c];if(this._settings[d]!==b._settings[d])return!1}return!0};a.aggregateSettings=["everything","geometry"];a.simpleSettings=["faces","lines","text"];a.allSettings=a.aggregateSettings.concat(a.simpleSettings);return a}();c.Visibility=a})(e.Internal||(e.Internal={}))})(e.HWF||(e.HWF={}))})(Communicator||
(Communicator={}));
